# Generated by Django 5.0.6 on 2024-06-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_post',
            field=models.BooleanField(default=False),
        ),
    ]
